Fixed a number of undefined named problems identified by PyFlakes
pinax/apps/blog/templatetags/switchcase.py:74: undefined name 'VariableDoesNotExist'
pinax/apps/blog/templatetags/switchcase.py:99: undefined name 'VariableDoesNotExist'
pinax/apps/signup_codes/views.py:29: undefined name 'ObjectDoesNotExist'
pinax/apps/signup_codes/views.py:30: undefined name 'Http404'
pinax/apps/tasks/views.py:149: undefined name 'user'
pinax/apps/topics/templatetags/topics_tags.py:47: undefined name 'tagname'
pinax/core/serializers/jsonfk.py:59: undefined name 'settings'
pinax/projects/sample_group_project/apps/basic_groups/views.py:4: redefinition of unused 'HttpResponseRedirect' from line 3
pinax/projects/sample_group_project/apps/basic_groups/views.py:107: undefined name 'message'

Signed-off-by: Brian Rosner <brosner@gmail.com>